services:
  app:
    build:
      context: .
      target: app
    image: covercraft:latest

  horizon:
    image: covercraft:latest

  scheduler:
    image: covercraft:latest

  postgres:
    ports:
      - "${DB_PORT_FORWARD:-5432}:5432"

  redis:
    ports:
      - "6380:6379"
